language: java
jdk:
  - openjdk8
script: mvn clean install --batch-mode -P integration-test
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  - jdk: openjdk8
branches:
  only:
    - master
  
